name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install DVC
        run: |
          pip install dvc[s3]

      - name: Configure AWS Credentials
        run: |
          dvc remote modify myremote access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          dvc remote modify myremote secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Pull data from DVC
        run: |
          dvc pull

      - name: Run DVC Pipeline
        run: |
          dvc repro

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t 2022bcs0044hadiqc/churn-mlops .

      - name: Push Docker Image
        run: |
          docker push 2022bcs0044hadiqc/churn-mlops